config/routes.rb
Rails.application.routes.draw do
  root to: "pages#show"

  get "/pages", to: "pages#show"

  get "/signup", to: "users#new"
  post "/users", to: "users#create"

  get "/users/:id/edit", to: "users#edit"
  patch "/users/:id", to: "users#update"
  delete "/users/:id", to: "users#destroy" 
  
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  get "/logout", to: "sessions#destroy"

  get "/profiles/new", to: "profiles#new"
  post "/profiles", to: "profiles#create"
  get "/profiles/:id", to: "profiles#show"
  get "/profiles/:id/edit", to: "profiles#edit"
  patch "/profiles/:id", to: "profiles#update"
  patch "/profiles/:id/pic", to: "profiles#change_pic"
  delete "/profiles/:id", to: "profiles#destroy"

  get "/trips", to: "trips#index"
  get "/trips/new", to: "trips#new"
  post "/trips", to: "trips#create"
  get "/trips/:id", to: "trips#show"
  get "/trips/:id/edit", to: "trips#edit"
  patch "/trips/:id", to: "trips#update"
  delete "/trips/:id", to: "trips#destroy"

  post "/favorites", to: "favorites#create"
  delete "/favorites/:id", to: "favorites#destroy"

  post "/friendships", to: "friendships#create"
  delete "/friendships/:id", to: "friendships#destroy"

  resources :conversations, only: [:index, :show, :destroy] do
    member do
      post :reply
    end
    member do
      post :restore
    end
    collection do
      delete :empty_trash
    end
  end

  resources :messages, only: [:new, :create]

end

app/models/profile.rb
class Profile < ApplicationRecord
  has_attached_file :profile_pic,
                    styles: { thumb: ["250x250#", :jpg] }
  validates_attachment :profile_pic, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }
  belongs_to :user
  validates :age, :location, :bio, presence: true
  validates :age, numericality: { only_integer: true, greater_than_or_equal_to: 18 }
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!

  def new
    if current_user.profile
      redirect_to "/profiles/#{current_user.profile.id}"
    else
      @profile = Profile.new
      render "new.html.erb"
    end
  end

  def create
    @profile = Profile.new(profile_params)
    if @profile.save
      flash[:success] = "Profile Successfully Created!"
      redirect_to "/profiles/#{current_user.profile.id}"
    else
      flash[:warning] = "Profile Not Created...Please Try Again!"
      render "new.html.erb"
    end
  end

  def show
    @profile = Profile.find_by(id: params[:id])
    if @profile
      render "show.html.erb"
    else
      flash[:warning] = "Profile Has Not Been Created Yet!"
      redirect_to "/pages"
    end
  end

  def edit
    @profile = Profile.find_by(id: params[:id])
    if @profile && (@profile.user.id == current_user.id)
      render "edit.html.erb"
    else
      redirect_to "/profiles/#{current_user.profile.id}"
    end
  end

  def update
    @profile = Profile.find_by(id: params[:id])
    @profile.assign_attributes(profile_params)
    if @profile.save
      flash[:success] = "Profile Successfully Updated!"
      redirect_to "/profiles/#{@profile.id}"
    else
      flash[:warning] = "Profile Not Updated...Please Try Again!"
      render "edit.html.erb"
    end
  end

  def change_pic
    @profile = Profile.find_by(id: params[:id])
    @profile.assign_attributes(profile_params)
    if @profile.save
      flash[:success] = "Profile Pic Successfully Updated!"
      redirect_to "/profiles/#{@profile.id}"
    else
      flash[:warning] = "Profile Pic Not Updated...Please Try Again!"
      render "edit.html.erb"
    end
  end

  def destroy
    @profile = Profile.find_by(id: params[:id])
    @profile.destroy
    flash[:success] = "Profile Successfully Deleted!"
    redirect_to "/profiles/new"
  end

  private

    def profile_params
      params.permit(:profile_pic, :age, :location, :bio).merge(user_id: current_user.id)
    end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/edit.html.erb
<section id="tsp_login_page" class="tsp-page-tpl">
  <div class="container">
      <div class="row">
          <div class="tsp-box-content tsp-page-acc">
            <div class="tsp-form-login col-md-6 col-sm-6 col-xs-6 tsp-full-xs tsp-no-padding-left">
                <div class="col-lg-offset-1 col-md-offset-1">
                    <h2>Edit Your TravelBuddy Profile:</h2>
                    <%= form_tag "/profiles/#{@profile.id}/pic", method: :patch, multipart: true, class: "tsp-form-site" do %>
                        <label class="white-text">Change/Upload Profile Pic:
                            <input type="file" name="profile_pic" class="button tsp-btn-site file-height">
                        </label>
                        <input type="submit" class="button tsp-btn-site file-height" value="Upload Photo">
                    <% end %>
                    <%= image_tag @profile.profile_pic.url(:thumb) %>
                    <br><br>
                    <%= form_tag "/profiles/#{@profile.id}", method: :patch, class: "tsp-form-site" do %>   
                        <div class="form-group">
                            <input type="text" name="age" value="<%= @profile.age %>" placeholder="Age">
                        </div>
                        <div class="form-group">
                            <input type="text" name="location" value="<%= @profile.location %>" placeholder="Location(City, State, Country)">
                        </div>
                        <div class="form-group">
                            <textarea name="bio" placeholder="Tell other users about your travel style"><%= @profile.bio %></textarea>
                        </div>
                        <button type="submit" class="tsp-btn-site">Edit Profile</button>
                    <% end %>
                </div>
            </div>
            <div class="col-md-6"><img class="profile-edit" src="/assets/succes-payment.jpg">
            </div>
          </div>
      </div>
  </div>
</section>

app/views/profiles/new.html.erb
<section id="tsp_login_page" class="tsp-page-tpl">
  <div class="container">
      <div class="row">
          <div class="tsp-box-content tsp-page-acc">
            <div class="tsp-form-login col-md-6 col-sm-6 col-xs-6 tsp-full-xs tsp-no-padding-left">
                <div class="col-lg-offset-1 col-md-offset-1">
                    <h2>Create Your TravelBuddy Profile:</h2>
                    <h3>Profile pic and all fields required</h3>
                    <%= form_tag "/profiles", method: :post, multipart: true, class: "tsp-form-site" do %>
                    <label>
                    Choose Profile Pic:
                    <input type="file" name="profile_pic" class="button tsp-btn-site file-height">
                    </label>      
                      <div class="form-group">
                        <input type="text" name="age" value="<%= @profile.age %>" placeholder="Age">
                      </div>
                      <div class="form-group">
                        <input type="text" name="location" value="<%= @profile.location %>" placeholder="Location(City, State, Country)">
                      </div>
                      <div class="form-group">
                        <textarea name="bio" placeholder="Tell other users about your travel style"><%= @profile.bio %></textarea>
                      </div>
                      <button type="submit" class="tsp-btn-site">Create Profile</button>
                    <% end %>
                </div>
            </div>
            <div class="col-md-6"><img class="profile-new" src="/assets/airplane-sunset.jpg">
            </div>
          </div>
      </div>
  </div>
</section>

app/views/profiles/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6">
      <% if @profile.user.id == current_user.id %>
        <h1>My Profile:</h1>
      <% else %>
        <h1><%= @profile.user.user_name %>'s Profile:</h1>
      <% end %>

      <img src="<%= @profile.profile_pic.url(:thumb) %>">
      <p><b>Name:</b> <span><%= @profile.user.first_name %> <%= @profile.user.last_name %></span></p>
      <p><b>Age:</b> <span><%= @profile.age %></span></p>
      <p><b>Location:</b> <span><%= @profile.location %></span></p>
      <p><b>A bit about me and travel:</b><br>
        <span><%= @profile.bio %></span></p>

      <% if @profile.user.id == current_user.id %>
        <div class="side-buttons">
          <a href="/profiles/<%= @profile.id %>/edit"><button class="button tsp-btn-site" style="width: 190px">Edit Your Profile</button></a>
          <%= button_to "Delete Your Profile", "/profiles/#{@profile.id}", method: :delete, class: "button tsp-btn-site pad-right", style: "margin-left: 10px", data: {confirm: 'Are you sure?'} %>
        </div>
        <br>
      <% else %>
        <div class="side-buttons">
          <%= button_to "Message #{@profile.user.user_name}", new_message_path, method: :get, params: { user: @profile.user.id }, class: "button tsp-btn-site" %>
          <% if current_user.not_friends(@profile.user.id) %>
            <%= button_to "Follow #{@profile.user.user_name}", "/friendships", params: {friend_id: @profile.user.id }, method: :post, class: "button tsp-btn-site pad-right", style: "margin-left: 15px" %>
          <% end %>
        </div>
        <br>
      <% end %>
    </div>

    <div class="col-md-6 right-align">
      <% if @profile.user.id == current_user.id %>
        <h3>My Trips:</h3>
      <% else %>
        <h3><%= @profile.user.user_name %>'s Trips:</h3>
      <% end %>
      <% if @profile.user.trips == [] %>
        <p class="white-text">No trips created yet</p><br>
      <% else %>
        <ul>
          <% @profile.user.trips.each do |trip| %>
            <li><a class="link-underline" href="/trips/<%= trip.id %>"><%= trip.destination.titleize %></a></li>
          <% end %>
        </ul><br>
      <% end %>

      <% if @profile.user.id == current_user.id %>
        <h3>Users I'm following:</h3>
      <% else %>
        <h3>Users <%= @profile.user.user_name %> is following:</h3>
      <% end %>
      <% if @profile.user.friends == [] %>
        <p class="white-text">Not following anyone</p><br>
      <% else %>
        <ul>
          <% @profile.user.friends.each do |friend| %>
            <li><a class="link-underline" href="/profiles/<%= friend.profile.id %>"><%= friend.user_name %></a>
            <% if @profile.user.id == current_user.id %>
              <%= link_to "(Unfollow)", "/friendships/#{friend.id}", method: :delete, class: "link-underline khaki-link", data: {confirm: 'Are you sure?'} %>
            <% end %>
            </li>
          <% end %>
        </ul><br>
      <% end %>

      <% if @profile.user.id == current_user.id %>
        <h3>Trips I'm interested in:</h3>
      <% else %>
        <h3>Trips <%= @profile.user.user_name %> is interested in:</h3>
      <% end %>
      <% if @profile.user.favorites == [] %>
        <p class="white-text">No bookmarked trips</p>
      <% else %>
        <ul>
          <% @profile.user.favorites.each do |favorite| %>
            <li><a class="link-underline" href="/trips/<%= favorite.trip.id %>"><%= favorite.trip.destination.titleize %></a>
            <% if @profile.user.id == current_user.id %>
              <%= link_to "(Remove)", "/favorites/#{favorite.id}", method: :delete, class: "link-underline khaki-link", data: {confirm: 'Are you sure?'} %>
            <% end %>
            </li>
          <% end %>
        </ul>
      <% end %>
    </div> 
  </div>
</div>