config/routes.rb
Rails.application.routes.draw do
  root to: "pages#show"

  get "/pages", to: "pages#show"

  get "/signup", to: "users#new"
  post "/users", to: "users#create"

  get "/users/:id/edit", to: "users#edit"
  patch "/users/:id", to: "users#update"
  delete "/users/:id", to: "users#destroy" 
  
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  get "/logout", to: "sessions#destroy"

  get "/profiles/new", to: "profiles#new"
  post "/profiles", to: "profiles#create"
  get "/profiles/:id", to: "profiles#show"
  get "/profiles/:id/edit", to: "profiles#edit"
  patch "/profiles/:id", to: "profiles#update"
  patch "/profiles/:id/pic", to: "profiles#change_pic"
  delete "/profiles/:id", to: "profiles#destroy"

  get "/trips", to: "trips#index"
  get "/trips/new", to: "trips#new"
  post "/trips", to: "trips#create"
  get "/trips/:id", to: "trips#show"
  get "/trips/:id/edit", to: "trips#edit"
  patch "/trips/:id", to: "trips#update"
  delete "/trips/:id", to: "trips#destroy"

  post "/favorites", to: "favorites#create"
  delete "/favorites/:id", to: "favorites#destroy"

  post "/friendships", to: "friendships#create"
  delete "/friendships/:id", to: "friendships#destroy"

  resources :conversations, only: [:index, :show, :destroy] do
    member do
      post :reply
    end
    member do
      post :restore
    end
    collection do
      delete :empty_trash
    end
  end

  resources :messages, only: [:new, :create]

end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_action :authenticate_user!
  before_action :get_mailbox
  before_action :get_conversation, except: [:index]
  before_action :get_box, only: [:index]

  def index
    if @box.eql? "inbox"
      @conversations = @mailbox.inbox
    elsif @box.eql? "sent"
      @conversations = @mailbox.sentbox
    else
      @conversations = @mailbox.trash
    end
    @conversations = @conversations.paginate(page: params[:page], per_page: 10)
  end

  def show
    @conversation.mark_as_read(current_user)
  end

  def reply
    current_user.reply_to_conversation(@conversation, params[:body])
    flash[:success] = "Reply sent"
    redirect_to conversation_path(@conversation)
  end

  def destroy
    @conversation.move_to_trash(current_user)
    flash[:success] = "The conversation was moved to trash."
    redirect_to conversations_path
  end

  def restore
    @conversation.untrash(current_user)
    flash[:success] = "The conversation was restored."
    redirect_to conversations_path
  end

  def empty_trash
    @mailbox.trash.each do |conversation|
      conversation.receipts_for(current_user).update_all(deleted: true)
    end
    flash[:success] = 'Your trash was emptied!'
    redirect_to conversations_path
  end

  private

    def get_box
      if params[:box].blank? or !["inbox","sent","trash"].include?(params[:box])
        params[:box] = "inbox"
      end
      @box = params[:box]
    end
  
    def get_mailbox
      @mailbox ||= current_user.mailbox
    end

    def get_conversation
      @conversation ||= @mailbox.conversations.find_by(id: params[:id])
    end
    
end

app/helpers/conversations_helper.rb
module ConversationsHelper

  def mailbox_section(title, current_box, opts = {})
    opts[:class] = opts.fetch(:class, '')
    opts[:class] += ' active' if title.downcase == current_box
    content_tag :li, link_to(title.capitalize, conversations_path(box: title.downcase)), opts
  end
  
end

app/views/conversations/_conversation.html.erb
<li class="list-group-item clearfix">
  <%= link_to conversation.subject, conversation_path(conversation), class: "visited-conv-link" %>
  <% if conversation.is_unread?(current_user) %>
    (New Message)
  <% end %>

  <div class="btn-group-vertical pull-right">
    <% if conversation.is_trashed?(current_user) %>
      <%= link_to 'Restore', restore_conversation_path(conversation), class: 'btn btn-xs btn-info', method: :post %>
    <% else %>
      <%= link_to 'Move to trash', conversation_path(conversation), class: 'btn btn-xs btn-danger', method: :delete,
                  data: {confirm: 'Are you sure?'} %>
    <% end %>
  </div>
</li>

app/views/conversations/index.html.erb
<div class="container">
  <h1>Your Conversations:</h1>
  <div class="row">
    <div class="col-sm-3">
      <ul class="nav nav-pills nav-stacked">
        <%= mailbox_section "inbox", @box %>
        <%= mailbox_section "sent", @box %>
        <%= mailbox_section "trash", @box %>
      </ul>
    </div>

    <div class="col-sm-9">
      <% if (@box == "trash") && (@conversations != []) %>
          <p><%= link_to "Empty trash", empty_trash_conversations_path, class: "btn btn-danger", method: :delete,
                data: {confirm: "Are you sure?"} %></p>
      <% elsif @conversations == [] %>
        <h1 class="mailbox-empty">Nothing here!</h1>
      <% end %>
      <ul class="list-group">
        <%= render partial: "conversations/conversation", collection: @conversations %>
      </ul>
      <%= will_paginate %>
    </div>
  </div>
</div>

app/views/conversations/show.html.erb
<div class="container">
  <h1>Conversation:</h1>

  <div class="panel panel-default">
    <div class="messages">
      <% receipts = @conversation.receipts_for(current_user).order(:created_at) %>
      <% receipts.each do |receipt| %>
        <% message = receipt.message %>
        <%= message.sender.name %>: 
        <%= message.body %>
        <br>
      <% end %>
    </div>
  </div>
  <%= form_tag reply_conversation_path(@conversation), method: :post do %>
    <div class="form-group">
      <%= text_area_tag "body", nil, cols: 3, class: "form-control", placeholder: "Enter your message here...", required: true %>
    </div>
    <%= submit_tag "Send Message", class: "button tsp-btn-site" %>
    <%= link_to "Back to Inbox", "/conversations", class: "button tsp-btn-site", style: "padding: 13px" %>
    <br><br>
  <% end %>
</div>